logs:
  - name: "system"
    level: "INFO"
    formatter: "%d%T%m%n"
    appenders:
      - type: "FileLogAppender"
        file: "log/test1.log"
      - type: "ConsoleLogAppender"

  - name: "logger2"
    level: "WARN"
    formatter: "%d%T%m%n"
    appenders:
      - type: "FileLogAppender"
        file: "log/test2.log"
      - type: "ConsoleLogAppender"
